import { useState } from "react";
import { Card } from "../../components/ui/Card";
import { Pill } from "../../components/ui/Pill";
import { Button } from "../../components/ui/Button";
import { Icon } from "../../components/ui/Icon";
import {
  financeCompanies,
  initialReports,
  periods,
  reportTypes,
  type Format,
  type Report,
  type ReportType,
} from "./data";

const fieldClass =
  "w-full rounded-md border border-line bg-paper-sunken px-3 py-2.5 text-[0.85rem] text-ink focus:border-jade-500 focus:outline-none";
const labelClass = "mb-1.5 block text-[0.74rem] font-semibold uppercase tracking-[0.06em] text-ink-faint";

export default function Reports() {
  const [type, setType] = useState<ReportType>("Portfolio summary");
  const [company, setCompany] = useState<string>("");
  const [period, setPeriod] = useState<string>(periods[0]);
  const [format, setFormat] = useState<Format>("PDF");
  const [reports, setReports] = useState<Report[]>(initialReports);

  const generate = () => {
    const co = company ? `${financeCompanies.find((c) => c.id === company)?.name} · ` : "";
    setReports((prev) => [
      {
        id: `rep-${Date.now()}`,
        name: `${type} — ${co}${period}`,
        by: "Admin",
        date: "Today",
        format,
      },
      ...prev,
    ]);
  };

  return (
    <div className="flex flex-col gap-6">
      {/* head */}
      <div className="flex flex-wrap items-end justify-between gap-4">
        <div>
          <p className="font-display text-[0.82rem] font-medium italic text-gold-600">Management information</p>
          <h2 className="mt-0.5 font-display text-[1.6rem] font-bold">Reports</h2>
          <p className="mt-0.5 text-[0.85rem] text-ink-soft">
            Generate portfolio, company, KPI, bonus and e-commerce reports — filterable and exportable to Excel and PDF.
          </p>
        </div>
      </div>

      {/* generator */}
      <Card className="p-5">
        <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
          <div>
            <label className={labelClass} htmlFor="rep-type">Report type</label>
            <select id="rep-type" className={fieldClass} value={type} onChange={(e) => setType(e.target.value as ReportType)}>
              {reportTypes.map((t) => (
                <option key={t} value={t}>{t}</option>
              ))}
            </select>
          </div>
          <div>
            <label className={labelClass} htmlFor="rep-company">Company</label>
            <select id="rep-company" className={fieldClass} value={company} onChange={(e) => setCompany(e.target.value)}>
              <option value="">All companies</option>
              {financeCompanies.map((c) => (
                <option key={c.id} value={c.id}>{c.name}</option>
              ))}
            </select>
          </div>
          <div>
            <label className={labelClass} htmlFor="rep-period">Period</label>
            <select id="rep-period" className={fieldClass} value={period} onChange={(e) => setPeriod(e.target.value)}>
              {periods.map((p) => (
                <option key={p} value={p}>{p}</option>
              ))}
            </select>
          </div>
          <div>
            <p className={labelClass}>Format</p>
            <div className="flex gap-2">
              {(["PDF", "Excel"] as Format[]).map((f) => (
                <button
                  key={f}
                  onClick={() => setFormat(f)}
                  className={`flex-1 rounded-md border px-2 py-2.5 text-[0.82rem] font-semibold transition-colors ${
                    format === f
                      ? "border-jade-500 bg-jade-100 text-jade-700"
                      : "border-line bg-paper-raised text-ink-soft hover:bg-paper-sunken"
                  }`}
                >
                  {f}
                </button>
              ))}
            </div>
          </div>
        </div>
        <div className="mt-4 flex justify-end">
          <Button variant="primary" size="md" icon="download" onClick={generate}>
            Generate report
          </Button>
        </div>
      </Card>

      {/* recent */}
      <Card>
        <div className="flex items-baseline justify-between border-b border-line-soft px-5 py-4">
          <h3 className="font-display text-[1.02rem] font-bold">Recently generated</h3>
          <span className="text-[0.76rem] text-ink-faint">{reports.length} reports</span>
        </div>
        <div className="thin-scroll overflow-x-auto">
          <table className="w-full text-[0.85rem]">
            <thead>
              <tr className="border-b border-line text-left">
                {["Report", "Format", "Generated by", "Date", ""].map((h, i) => (
                  <th
                    key={h || "act"}
                    className={`whitespace-nowrap px-4 py-2.5 text-[0.7rem] font-bold uppercase tracking-wider text-ink-faint ${i >= 3 ? "text-right" : ""}`}
                  >
                    {h}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {reports.map((r) => (
                <tr key={r.id} className="border-b border-line-soft last:border-0 hover:bg-paper-sunken">
                  <td className="px-4 py-3 font-semibold">
                    <span className="flex items-center gap-2.5">
                      <Icon name="reports" className="h-4.5 w-4.5 shrink-0 text-jade-600" />
                      {r.name}
                    </span>
                  </td>
                  <td className="px-4 py-3">
                    <Pill tone={r.format === "PDF" ? "critical" : "good"} dot={false}>{r.format}</Pill>
                  </td>
                  <td className="whitespace-nowrap px-4 py-3 text-ink-soft">{r.by}</td>
                  <td className="tnum whitespace-nowrap px-4 py-3 text-right text-ink-soft">{r.date}</td>
                  <td className="px-4 py-3 text-right">
                    <Button variant="ghost" size="sm" icon="download">Download</Button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>
    </div>
  );
}
